### ISSUE TITLE
List of shingles changes when I restart PC

### ISSUE THREAD

**Issue by mohammad-saber** [reymond-group/map4#11]
Hi, Thank you for sharing your great work. 

I am trying to explain every bit in MAP FingerPrint as bit vector (bits with value 1) for the purpose of explainability of ML model trained on MAP fingerprint.  

I am trying to find which shingle is related to a specific bit in bit vector by reverse modulo operation. I had a difficulty which is explained below. I am very sorry that my question is very long. Thank you for your time to read my question. 

----------------------------
I get shingles by setting "return_strings=True" for a specific molecule. It returns a list of shingles. 

I noticed that when I restart PC, I get list of shingles but in a different order. 

For example, one time I get shingles as [shingle A, shingle B, shingle C]. But, the next day, I get [shingle C, shingle A, shingle B].

Also, when I apply "MHFPEncoder.hash" to get SHA-1 hash values for shingles, sometimes (not always) I get different values after restarting PC. For example, for shingle A, I get SHA-1 value of 962277111. The other day, I get SHA-1 value of 3766998768 for the same shingle.

It is interesting that when I get bit vector (by setting is_folder = True), bit vector is the same for a specific molecule. There is no change in bit vector. 
Bit vector is obtained by modulo operation as below: 

```
folded = np.zeros(nBits, dtype=np.uint8)
folded[hash_values % nBits] = 1 
```  

Since hash values change after restarting PC, remainder values will change. And therefore, different indexes in "folded" vector will get value of 1.

**My conclusion:**
Every time I get bit vector, the bits with value "1" may refer to different shingles. For example, if bit vector is: 
[0 1 0 0 1 ......... 0 1]

The second bit has value of 1. It may be related to shingle A. But, after restarting PC, it may represent shingle B.
Could you please let me know if my understanding is correct? 

I guess the formula used to convert hash values into integer will sometimes (not always) produce different integer values for the same shingle after restarting PC:

```
        hash_values = []

        for t in shingling:
            hash_values.append(struct.unpack("<I", sha1(t).digest()[:4])[0])
```

When I use `"MHFPEncoder", ".hash" method` and the above formula, sometimes I get different hash values for the same shingles.    

----------------------------------------------

My purpose is to find which shingle is related to a specific bit. If fingerprint representation changes by restarting PC or python kernel, it will not be possible to relate specific bit to a specific shingle or shingles in case of bit collision. 

I really appreciate it if you have any idea to help me on this issue.

**Comment by mohammad-saber** [comment]
I found the reason for this problem. 
Since we pass shingles as a "set" to get SHA-1 values, and "set" in an un-ordered data-type, the order of shingles change. In fact, hash values don't change for the same input. 
When I passed shingles as a "list", the problem was solved.

**Comment by alicecapecchi** [comment]
Hi Mohammad,
Sorry for the late reply, I am happy that you found a solution.
Did you check for redundancy in the list of shingles? Because that was the reason why I was returning a set. If you haven't found a solution yet, generating a set and then converting it to an ordered list should work.
Cheers,
Alice
