### ISSUE TITLE
Allow a range of python version

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [reymond-group/map4#14]
Hi,

I'm not deeply familiarized with `conda`, but could it be possible to allow the library to be installed in a wider range of Python versions?

Looking at the [package match specification](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#package-match-specifications) documentation, I think it could _possibly_ be achieved by modifying this line in the `environment.yml` file. ( Please correct me if I'm wrong )

https://github.com/reymond-group/map4/blob/1457602793f0438a77ee9578ef89ab9a20840c00/environment.yml#L7

To something like the following

```yaml
 - python>=3.6,<=3.9
```

or with a space

```yaml
 - python >=3.6,<=3.9
```

Thanks!

**Comment by alicecapecchi** [comment]
Hi, thanks for the suggestion. 
Probably the code would work with newer versions of python, and yes what you are suggesting should be correct. 
However, currently I don't have the time to test MAP4 with multiple version of python, and I don't want to publish untested modifications. 
If you need a different python version you can change the environment locally (as you suggested) and then install it.
Cheers,
Alice
