### ISSUE TITLE
Relationship between distance & similarity?

### ISSUE THREAD

**Issue by mohammad-saber** [reymond-group/map4#8]
I would like to confirm the relationship between distance and similarity of molecules. When we calculate distance as below:

```
ENC = tm.Minhash(dim)
ENC.get_distance(map4_a, map4_b)
```

I guess similarity will be: 

`similarity = 1 - distance`

I really appreciate it if you could confirm the similarity calculation. 
Thank you.

**Comment by alicecapecchi** [comment]
Yes, 
actually the approximated Jaccard distance between two MinHashed fingerprint (which is what you calculate with the encoder) can be also directly calculated in Python as:
`distance = 1 - np.float(np.count_nonzero(fp1 == fp2)) / np.float(len(fp1))`
Please not that If you are using the folded version, the distance should be calculated with the true Jaccard distance (or other classical distance calculations).
